<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>Introduction</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: #990073
   }

   pre .number {
     color: #099;
   }

   pre .comment {
     color: #998;
     font-style: italic
   }

   pre .keyword {
     color: #900;
     font-weight: bold
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: #d14;
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>



<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h2>Introduction</h2>

<p>The EVALFQ provides an open assess online service enabling <b>(1)</b> the label-free proteome quantification (LFQ) based on three quantification measurements <i>SWATH-MS</i>, <i>Peak Intensity</i> and <i>Spectral Counting</i>, <b>(2)</b> the evaluation of LFQ performances from multiple perspectives and <b>(3)</b> the identification of the optimal LFQs based on comprehensive performance ranking. The EVALFQ mainly includes two function <code>lfq_access</code> and <code>lfq_spiked</code> to realize not only AUTOMATICALLY detects the diverse formats of data generated by all quantification software, but also provides the most complete set of processing methods among available tools, which including the methods of <b><i>transformation</i></b>, <b><i>pretreatment</i></b> (centering, scaling &amp; normalization) and missing value <b><i>imputation</i></b>.</p>

<p>This tutorial will walk the readers through an example analysis (as follow &#39;Examples&#39;). </p>

<h2>Installation</h2>

<pre><code class="R"># download the source package of EVALFQ_0.1.0.tar.gz and install it.
install.packages(pkg = &#39;EVALFQ_0.1.0.tar.gz&#39;)

# Alternatively EVALFQ can be installed from GitHub:
# install.packages(&quot;devtools&quot;)
devtools::install_github(&quot;idrblab/EVALFQ&quot;)
library(EVALFQ)

# EVALFQ package depends on several packages, which can be installed using the below commands:
if (!requireNamespace(&quot;BiocManager&quot;, quietly = TRUE))
install.packages(&quot;BiocManager&quot;)
BiocManager::install(&quot;Biobase&quot;)
BiocManager::install(&quot;BiocGenerics&quot;)
BiocManager::install(&quot;ROTS&quot;)
BiocManager::install(&quot;limma&quot;)
BiocManager::install(&quot;ProteoMM&quot;)
BiocManager::install(&quot;impute&quot;)
BiocManager::install(&quot;pcaMethods&quot;)
BiocManager::install(&quot;vsn&quot;)
BiocManager::install(&quot;affy&quot;)
devtools::install_github(&quot;cran/metabolomics&quot;)
</code></pre>

<h2>Usage</h2>

<p><code>library(EVALFQ)</code></p>

<h4>1. Prepare input file for evaluating label-free proteome quantification.</h4>

<pre><code class="(r)">my_data &lt;- PrepareInuputFiles(acquisitionmethods, rawdataset, lable)
</code></pre>

<p><code>acquisitionmethods</code> 
Input the corresponding &ldquo;number&rdquo; of acquisition techniques as follows: <br>
If set 1, the user chooses to process the data based on SWATH-MS. <br>
If set 2, the user chooses to process the data based on Peak Intensity. <br>
If set 3, the user chooses to process the data based on Spectral Counting.</p>

<p><code>rawdataset</code> 
Input the name of your raw dataset directly obtained from software.<br>
EVALFQ supports a variety of data generated by 18 kinds of popular quantification software. <br>
The format of each software could be readily found as follows (<b>Right Click to Save</b>). <br>
(1) A list of software for pre-processing the data acquired based on SWATH-MS.<br>
<a href='https://idrblab.org/evalfq/download/SWATH_MS/DIAumpire_ProteinSummary.csv'>DIA-UMPIRE</a>; <a href='https://idrblab.org/evalfq/download/SWATH_MS/example_OpenSWATH.csv'>OpenSWATH</a>; <a href='https://idrblab.org/evalfq/download/SWATH_MS/ProtSummary_201604130950.csv'>PeakView</a>; <a href='https://idrblab.org/evalfq/download/SWATH_MS/Skyline_HYE124_TTOF6600_32fix_it1_IntLibFixed1603.tsv'>Skyline</a>; <a href='https://idrblab.org/evalfq/download/SWATH_MS/example_Spectronaut.tsv'>Spectronaut</a> <br>
(2) A list of software for pre-processing the data acquired based on Peak Intensity.<br>
<a href='https://idrblab.org/evalfq/download/Peak_Intensity/MaxQuant_proteinGroups_LFQ.txt'>MaxQuant</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/example_MFPaQ_Peak_Intensity.csv'>MFPaQ</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/example_OpenMS.csv'>OpenMS</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/proteinGroups_Peak_Intensity.txt'>PEAKS</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/Progenesis_guide_Output.csv'>Progenesis</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/example_Proteios_SE.csv'>Proteios SE</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/scaffold-label-free_Peak_Intensity.csv'>Scaffold</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/example_Proteome_Discoverer.csv'>Thermo Proteome Discoverer</a> <br>
(3) A list of software for pre-processing the data acquired based on Spectral Counting.<br>
<a href='https://idrblab.org/evalfq/download/Peak_Intensity/abacus_data_output.csv'>Abacus</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/example_Census.txt'>Census</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/example_DTASelect.csv'>DTASelect</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/example_IRMa-hEIDI.csv'>IRMa-hEIDI</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/MaxQuant_proteinGroups_SC.txt'>MaxQuant</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/example_MFPaQ_Spectral_Counting.csv'>MFPaQ</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/example_ProteinProphet.csv'>ProteinProphet</a>; <a href='https://idrblab.org/evalfq/download/Peak_Intensity/scaffold-label-free_Spectral_Counting.csv'>Scaffold</a> <br></p>

<p><code>lable</code> 
Input the label of your dataset.</p>

<h4>2. Conduct LFQ and assess performance of all possible LFQ workflows.</h4>

<pre><code class="(r)">allranks &lt;- lfqevalueall(data_q,
                         assum_a = &quot;Y&quot;,
                         assum_b = &quot;Y&quot;,
                         assum_c = &quot;Y&quot;,
                         Ca = &quot;1&quot;, 
                         Cb = &quot;1&quot;, 
                         Cc = &quot;1&quot;, 
                         Cd = &quot;1&quot;)
</code></pre>

<p><code>data_q</code> 
This input file should be numeric type except the first and second column containing the names and label (control or case) of the studied samples, respectively. The intensity data should be provided in this input file with the following order: samples in row and proteins/peptides in column. Missing value (NA) of protein intensity are allowed.</p>

<p><code>assum_a</code> 
All proteins were assumed to be equally important.<br>
The authors will be asked to input a letter “Y” to indicate the corresponding assumption is held for the studied dataset and a letter “N” to denote the opposite.</p>

<p><code>assum_b</code> 
The level of protein abundance was assumed to be constant among all samples.<br>
The authors will be asked to input a letter “Y” to indicate the corresponding assumption is held for the studied dataset and a letter “N” to denote the opposite.</p>

<p><code>assum_c</code> 
The intensities of the vast majority of the proteins were assumed to be unchanged under the studied conditions.<br>
The authors will be asked to input a letter “Y” to indicate the corresponding assumption is held for the studied dataset and a letter “N” to denote the opposite.</p>

<p><code>Ca</code> 
Criterion (a): precision of LFQ based on the proteomes among replicates<sup>1</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (a).<br>
If set 0, the user excludes Criterion (a) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cb</code> 
Criterion (b): classification ability of LFQ between distinct sample groups<sup>2</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (b).<br>
If set 0, the user excludes Criterion (b) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cc</code> 
Criterion &copy;: differential expression analysis by reproducibility-optimization<sup>3</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion &copy;.<br>
If set 0, the user excludes Criterion &copy; from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cd</code> 
Criterion (d): reproducibility of the identified protein markers among different datasets<sup>4</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (d).<br>
If set 0, the user excludes Criterion (d) from performance assessment.<br>
The default setting of this value is “1”.</p>

<h4>3. Conduct LFQ and assess performance by collectively considering the spiked proteins.</h4>

<pre><code class="(r)">allranks &lt;- lfqspikedall(data_s,
                         spiked,
                         assum_a = &quot;Y&quot;,
                         assum_b = &quot;Y&quot;,
                         assum_c = &quot;Y&quot;,
                         Ca = &quot;1&quot;, 
                         Cb = &quot;1&quot;, 
                         Cc = &quot;1&quot;, 
                         Cd = &quot;1&quot;,
                         Ce = &quot;1&quot;)
</code></pre>

<p><code>data_s</code> 
This input file should be numeric type except the first and second column containing the names and label (control or case) of the studied samples, respectively. The intensity data should be provided in this input file with the following order: samples in row and proteins/peptides in column. Missing value (NA) of protein intensity are allowed.</p>

<p><code>spiked</code> 
The file should provide the concentrations of known proteins (such as spiked proteins). This file is required, if the user want to conduct assessment using criteria (e) This file should contain the class of samples and the Sample ID. The Sample ID should be unique and defined by the preference of EVALFQ users, and the class of samples refers to the group of Sample ID. The ID of the spiked proteins should be consistent in both “data_s&quot; and &ldquo;spiked”. Detail information are described in the online “Example”.</p>

<p><code>assum_a</code> 
All proteins were assumed to be equally important.<br>
The authors will be asked to input a letter “Y” to indicate the corresponding assumption is held for the studied dataset and a letter “N” to denote the opposite.</p>

<p><code>assum_b</code> 
The level of protein abundance was assumed to be constant among all samples.<br>
The authors will be asked to input a letter “Y” to indicate the corresponding assumption is held for the studied dataset and a letter “N” to denote the opposite.</p>

<p><code>assum_c</code> 
The intensities of the vast majority of the proteins were assumed to be unchanged under the studied conditions.<br>
The authors will be asked to input a letter “Y” to indicate the corresponding assumption is held for the studied dataset and a letter “N” to denote the opposite.</p>

<p><code>Ca</code> 
Criterion (a): precision of LFQ based on the proteomes among replicates<sup>1</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (a).<br>
If set 0, the user excludes Criterion (a) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cb</code> 
Criterion (b): classification ability of LFQ between distinct sample groups<sup>2</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (b).<br>
If set 0, the user excludes Criterion (b) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cc</code> 
Criterion &copy;: differential expression analysis by reproducibility-optimization<sup>3</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion &copy;.<br>
If set 0, the user excludes Criterion &copy; from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cd</code> 
Criterion (d): reproducibility of the identified protein markers among different datasets<sup>4</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (d).<br>
If set 0, the user excludes Criterion (d) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Ce</code> 
Criterion (e): accuracy of LFQ based on spiked and background proteins<sup>5</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (e).<br>
If set 0, the user excludes Criterion (e) from performance assessment.<br>
The default setting of this value is “1”.</p>

<h4>4. Draw heatmap and save as EVALFQ-OUTPUT.Figure-Top.XXX.workflows.pdf.</h4>

<pre><code class="(r)">lfqvisualize(object, top = 100)
</code></pre>

<p><code>object</code> 
The input is the output file of the <code>lfq_access</code> or <code>lfq_spiked</code>.</p>

<p><code>top</code>
The default &#39;top&#39; value is 100.<br>
You can view the top ranking heatmap you want.<br></p>

<h4>5. Conduct LFQ and assess performance of one specific LFQ workflow.</h4>

<pre><code class="(r)">res &lt;- lfqevalupart(data_q,
                    selectFile,
                    Ca = &quot;1&quot;, 
                    Cb = &quot;1&quot;, 
                    Cc = &quot;1&quot;, 
                    Cd = &quot;1&quot;)
</code></pre>

<p><code>data_q</code> 
Same as the description of the &#39;lfq_access&#39; above.</p>

<p><code>selectFile</code> 
Input the name of your prefered strategies. Sample data of this data type is in the working directory (in github) “idrblab/EVALFQ/data/selectworkflows.rda”.</p>

<p><code>Ca</code> 
Criterion (a): precision of LFQ based on the proteomes among replicates<sup>1</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (a).<br>
If set 0, the user excludes Criterion (a) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cb</code> 
Criterion (b): classification ability of LFQ between distinct sample groups<sup>2</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (b).<br>
If set 0, the user excludes Criterion (b) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cc</code> 
Criterion &copy;: differential expression analysis by reproducibility-optimization<sup>3</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion &copy;.<br>
If set 0, the user excludes Criterion &copy; from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cd</code> 
Criterion (d): reproducibility of the identified protein markers among different datasets<sup>4</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (d).<br>
If set 0, the user excludes Criterion (d) from performance assessment.<br>
The default setting of this value is “1”.</p>

<h4>6. Conduct LFQ and assess performance by collectively considering the spiked proteins.</h4>

<pre><code class="(r)">res &lt;- lfqspikepart(data_s,
                    spiked,
                    selectFile,
                    Ca = &quot;1&quot;, 
                    Cb = &quot;1&quot;, 
                    Cc = &quot;1&quot;, 
                    Cd = &quot;1&quot;)
</code></pre>

<p><code>data_s</code> 
Same as the description of the &#39;lfq_spiked&#39; above.</p>

<p><code>spiked</code> 
Same as the description of the &#39;lfq_spiked&#39; above.</p>

<p><code>selectFile</code> 
Input the name of your prefered strategies. Sample data of this data type is in the working directory (in github) “idrblab/EVALFQ/data/selectworkflows.rda”.</p>

<p><code>Ca</code> 
Criterion (a): precision of LFQ based on the proteomes among replicates<sup>1</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (a).<br>
If set 0, the user excludes Criterion (a) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cb</code> 
Criterion (b): classification ability of LFQ between distinct sample groups<sup>2</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (b).<br>
If set 0, the user excludes Criterion (b) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cc</code> 
Criterion &copy;: differential expression analysis by reproducibility-optimization<sup>3</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion &copy;.<br>
If set 0, the user excludes Criterion &copy; from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Cd</code> 
Criterion (d): reproducibility of the identified protein markers among different datasets<sup>4</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (d).<br>
If set 0, the user excludes Criterion (d) from performance assessment.<br>
The default setting of this value is “1”.</p>

<p><code>Ce</code> 
Criterion (e): accuracy of LFQ based on spiked and background proteins<sup>5</sup>.<br>
If set 1, the user chooses to assess LFQ workflows using Criterion (e).<br>
If set 0, the user excludes Criterion (e) from performance assessment.<br>
The default setting of this value is “1”.</p>

<h2>Examples</h2>

<pre><code class="(r)"># Step 1: Prepare input file for evaluating label-free proteome quantification.

my_df &lt;- PrepareInuputFiles(acquisitionmethods = &quot;2&quot;, 
                            rawdataset = &quot;MaxQuant_proteinGroups_LFQ.txt&quot;, 
                            lable = &quot;MaxQuant_LFQ_Label.txt&quot;)
OR

my_df &lt;- read.csv(file = &quot;EVALFQ_Unified_Data.csv&quot;, header = TRUE, stringsAsFactors = FALSE)

# Note: the file should be in the format of Comma-Separated Values (CSV), which provides the intensity data of proteins/peptides. This input file should be numeric type except the first and second column containing the names and label (control or case) of the studied samples, respectively. The intensity data should be provided in this input file with the following order: samples in row and proteins/peptides in column. Missing value (NA) of protein intensity are allowed.
</code></pre>

<p>The format of input files could be readily found HERE:<br>
<a href='https://idrblab.org/evalfq/download/Peak_Intensity/MaxQuant_proteinGroups_LFQ.txt'>MaxQuant_proteinGroups_LFQ.txt</a><br>
<a href='https://idrblab.org/evalfq/download/Peak_Intensity/MaxQuant_LFQ_Label.txt'>MaxQuant_LFQ_Label.txt</a><br>
<a href='https://idrblab.org/evalfq/download/EVALFQ_Unified_Data.csv'>EVALFQ_Unified_Data.csv</a></p>

<pre><code class="r">load(&quot;../data/my_spiked.rda&quot;)
dim(my_spiked)
</code></pre>

<pre><code>## [1]    6 3410
</code></pre>

<pre><code class="r">head(my_spiked[1:4])
</code></pre>

<pre><code>##   SampleName   Label A0A023T778.P61327.Q9CQL1 A0A087WNT1.A0A087WQE6.P83940
## 1 QExHF03751 sample1                  1753266                      2605095
## 2 QExHF03761 sample1                  3692243                      2345378
## 3 QExHF03771 sample1                  3376227                      3250551
## 4 QExHF03755 sample3                  3465725                      2243918
## 5 QExHF03765 sample3                  2659221                      2139299
## 6 QExHF03775 sample3                  3296311                      1945067
</code></pre>

<pre><code class="r">load(&quot;../data/spiked_data.rda&quot;)
dim(spiked_data)
</code></pre>

<pre><code>## [1]  6 14
</code></pre>

<pre><code class="r">head(spiked_data[1:5])
</code></pre>

<pre><code>##              Label P37840 P02754 P02671 P02675
## QExHF03751 sample1    1.0    0.5     10     10
## QExHF03761 sample1    1.0    0.5     10     10
## QExHF03771 sample1    1.0    0.5     10     10
## QExHF03755 sample3    0.5    5.0      1      1
## QExHF03765 sample3    0.5    5.0      1      1
## QExHF03775 sample3    0.5    5.0      1      1
</code></pre>

<pre><code class="(r)"># Step 1: conduct LFQ and assess performance of all possible LFQ workflows or assess performance by collectively considering the spiked proteins.
# Note: the file should be in the format of Comma-Separated Values (CSV), which provides the intensity data of proteins/peptides. This input file should be numeric type except the first and second column containing the names and label (control or case) of the studied samples, respectively. The intensity data should be provided in this input file with the following order: samples in row and proteins/peptides in column. Missing value (NA) of protein intensity are allowed.

allranks &lt;- lfqevalueall(data_q = my_df,
                         assum_a = &quot;Y&quot;,
                         assum_b = &quot;Y&quot;,
                         assum_c = &quot;Y&quot;,
                         Ca = &quot;1&quot;,
                         Cb = &quot;1&quot;,
                         Cc = &quot;1&quot;,
                         Cd = &quot;1&quot;)

OR

# Note: the file should be in the format of Comma-Separated Values (CSV), which provides the concentrations of known proteins (such as spiked proteins). This file is required, if the user want to conduct assessment using criteria (e) This file should contain the class of samples and the Sample ID. The Sample ID should be unique and defined by the preference of EVALFQ users, and the class of samples refers to the group of Sample ID. The ID of the spiked proteins should be consistent in both &quot;my_spiked&quot; and &quot;spiked_data&quot;.

allranks &lt;- lfqspikedall(data_s = my_spiked,
                         spiked = spiked_data,
                         assum_a = &quot;Y&quot;,
                         assum_b = &quot;Y&quot;,
                         assum_c = &quot;Y&quot;,
                         Ca = &quot;1&quot;, 
                         Cb = &quot;1&quot;, 
                         Cc = &quot;1&quot;, 
                         Cd = &quot;1&quot;,
                         Ce = &quot;1&quot;)

# Note: &#39;allranks&#39; containing all information of performance assessment, criteria selected and ranking.
</code></pre>

<pre><code class="r">load(&quot;../data/allranks.rda&quot;)
head(allranks)
</code></pre>

<pre><code>##                     Rank.OverallRank Rank.Precision Rank.Classification.Ability
## BOX-NON-ATO-MAD-SVD                1            520                           1
## BOX-NON-ATO-MAD-KNN                2            518                           1
## BOX-NON-ATO-MAD-NON                3            519                           1
## BOX-NON-ATO-MAD-BAK                4            525                           1
## BOX-NON-ATO-MAD-CEN                4            525                           1
## BOX-NON-ATO-MAD-BPC                6            528                           1
##                     Rank.Differential.Expression Rank.Accuracy Value.Precision
## BOX-NON-ATO-MAD-SVD                           32           335    0.0185807289
## BOX-NON-ATO-MAD-KNN                           58           324    0.0180662010
## BOX-NON-ATO-MAD-NON                           63           323    0.0181988132
## BOX-NON-ATO-MAD-BAK                           66           329    0.0190352798
## BOX-NON-ATO-MAD-CEN                           66           329    0.0190352798
## BOX-NON-ATO-MAD-BPC                          105           321    0.0190409157
##                     Value.Classification.Ability Value.Differential.Expression
## BOX-NON-ATO-MAD-SVD                 1.0000000000                  0.0004454208
## BOX-NON-ATO-MAD-KNN                 1.0000000000                  0.0004774402
## BOX-NON-ATO-MAD-NON                 1.0000000000                  0.0004913414
## BOX-NON-ATO-MAD-BAK                 1.0000000000                  0.0004992509
## BOX-NON-ATO-MAD-CEN                 1.0000000000                  0.0004992509
## BOX-NON-ATO-MAD-BPC                 1.0000000000                  0.0005264378
##                     Value.Accuracy
## BOX-NON-ATO-MAD-SVD   0.0004870352
## BOX-NON-ATO-MAD-KNN   0.0004112066
## BOX-NON-ATO-MAD-NON   0.0004091181
## BOX-NON-ATO-MAD-BAK   0.0004422784
## BOX-NON-ATO-MAD-CEN   0.0004422784
## BOX-NON-ATO-MAD-BPC   0.0004045245
</code></pre>

<pre><code class="(r)"># Step 2: a heatmap illustrating the performance ranking of all LFQ workflows based on the criteria selected by user.

lfqvisualize(object = &quot;EVALFQ-OUTPUT.Data-Overall.Ranking.csv&quot;, top = 100)

# Note: the &#39;EVALFQ-OUTPUT.Figure-Top.XXX.workflows.pdf&#39; would be successfully saved in the current path. Please use &#39;getwd()&#39; to find the current path!
</code></pre>

<pre><code class="(r)"># Users can also use EVALFQ by selecting one specific LFQ as follows:

res &lt;- lfqevalupart(data_q = my_df,
                    selectFile = selectworkflows,
                    Ca = &quot;1&quot;, 
                    Cb = &quot;1&quot;, 
                    Cc = &quot;1&quot;, 
                    Cd = &quot;1&quot;)

OR

res &lt;- lfqspikepart(data_s = my_spiked,
                    spiked = spiked_data,
                    selectFile = selectworkflows,
                    Ca = &quot;1&quot;, 
                    Cb = &quot;1&quot;, 
                    Cc = &quot;1&quot;, 
                    Cd = &quot;1&quot;)            

Note: please select the appropriate number code represents transformation, centering, scaling, normalization, imputation methods (See above details).
</code></pre>

<p>Should you have any questions, please contact Jianbo Fu at <a href="mailto:fujianbo@zju.edu.cn">fujianbo@zju.edu.cn</a></p>

<h2>References</h2>

<ol>
<li><p>Kuharev J, Navarro P, Distler U, <i>et al</i>.  In-depth evaluation of software tools for data-independent acquisition based label-free quantification. <i>Proteomics</i> 2015;15:3140–3151.</p></li>
<li><p>Griffin NM, Yu J, Long F, <i>et al</i>.  Label-free, normalized quantification of complex mass spectrometry data for proteomic analysis. <i>Nat Biotechnol</i> 2010;28:83–89.</p></li>
<li><p>Risso D, Ngai J, Speed TP, <i>et al</i>.  Normalization of RNA-seq data using factor analysis of control genes or samples. <i>Nat Biotechnol</i> 2014;32:896–902.</p></li>
<li><p>Wang X, Gardiner EJ, Cairns MJ. Optimal consistency in microRNA expression analysis using reference-gene-based normalization. <i>Mol Biosyst</i> 2015;11:1235–1240.</p></li>
<li><p>Navarro P, Kuharev J, Gillet LC, <i>et al</i>.  A multicenter study benchmarks software tools for label-free proteome quantification. <i>Nat Biotechnol</i> 2016;34:1130–1136.</p></li>
<li><p>Lo, K., and Gottardo, R. (2012) Flexible mixture modeling via the multivariate t distribution with the Box-Cox transformation: An alternative to the skew-t distribution. <i>Stat. Comput</i>. 22, 33–52.</p></li>
<li><p>Callister, S. J., Barry, R. C., Adkins, J. N., Johnson, E. T., Qian, W. J., Webb-Robertson, B. J., Smith, R. D., and Lipton, M. S. (2006) Normalization approaches for removing systematic biases associated with mass spectrometry and label-free proteomics. <i>J. Proteome Res</i>. 5, 277–286.</p></li>
<li><p>van den Berg, R. A., Hoefsloot, H. C., Westerhuis, J. A., Smilde, A. K., and van der Werf, M. J. (2006) Centering, scaling, and transformations: Improving the biological information content of metabolomics data. <i>BMC Genomics</i> 7, 142.</p></li>
<li><p>Wang, S. Y., Kuo, C. H., and Tseng, Y. J. (2013) Batch normalizer: A fast total abundance regression calibration method to simultaneously adjust batch and injection order effects in liquid chromatography/time-of-flight mass spectrometry-based metabolomics data and comparison with current calibration methods. <i>Anal. Chem</i>. 85, 1037–1046.</p></li>
<li><p>Wang, X., Zhang, A., Han, Y., Wang, P., Sun, H., Song, G., Dong, T., Yuan, Y., Yuan, X., Zhang, M., Xie, N., Zhang, H., Dong, H., and Dong, W. (2012) Urine metabolomics analysis for biomarker discovery and detection of jaundice syndrome in patients with liver disease. <i>Mol. Cell. Proteomics</i> 11, 370 –380.</p></li>
<li><p>Di Guida, R., Engel, J., Allwood, J. W., Weber, R. J., Jones, M. R., Sommer, U., Viant, M. R., and Dunn, W. B. (2016) Non-targeted UHPLC-MS metabolomic data processing methods: a comparative investigation of normalisation, missing value imputation, transformation and scaling. <i>Metabolomics</i> 12, 93.</p></li>
<li><p>Smilde, A. K., van der Werf, M. J., Bijlsma, S., van der Werff-van der Vat, B. J., and Jellema, R. H. (2005) Fusion of mass spectrometry-based metabolomics data. <i>Anal. Chem</i>. 77, 6729 – 6736.</p></li>
<li><p>Cox, J., Hein, M. Y., Luber, C. A., Paron, I., Nagaraj, N., and Mann, M. (2014) Accurate proteome-wide label-free quantification by delayed normalization and maximal peptide ratio extraction, termed MaxLFQ. <i>Mol. Cell. Proteomics</i> 13, 2513–2526.</p></li>
<li><p>Ballman, K. V., Grill, D. E., Oberg, A. L., and Therneau, T. M. (2004) Faster cyclic loess: normalizing RNA arrays via linear models. <i>Bioinformatics</i> 20, 2778 –2786.</p></li>
<li><p>Va¨ likangas, T., Suomi, T., and Elo, L. L. (2018) A systematic evaluation of normalization methods in quantitative label-free proteomics. <i>Brief Bioinform</i>. 19, 1–11.</p></li>
<li><p>Leek, J. T., and Storey, J. D. (2007) Capturing heterogeneity in gene expression studies by surrogate variable analysis. <i>PLoS Genet</i>. 3, 1724 –1735.</p></li>
<li><p>Karpievitch, Y. V., Taverner, T., Adkins, J. N., Callister, S. J., Anderson, G. A., Smith, R. D., and Dabney, A. R. (2009) Normalization of peak intensities in bottom-up MS-based proteomics using singular value decomposition. <i>Bioinformatics</i> 25, 2573–2580.</p></li>
<li><p>Adriaens, M. E., Jaillard, M., Eijssen, L. M., Mayer, C. D., and Evelo, C. T. (2012) An evaluation of two-channel ChIP-on-chip and DNA methylation microarray normalization strategies. <i>BMC Genomics</i> 13, 42.</p></li>
<li><p>Craig, A., Cloarec, O., Holmes, E., Nicholson, J. K., and Lindon, J. C. (2006) Scaling and normalization effects in NMR spectroscopic metabonomic data sets. <i>Anal. Chem</i>. 78, 2262–2267.</p></li>
<li><p>Fundel, K., Haag, J., Gebhard, P. M., Zimmer, R., and Aigner, T. (2008) Normalization strategies for mRNA expression data in cartilage research. <i>Osteoarthritis Cartilage</i> 16, 947–955.</p></li>
<li><p>De Livera, A. M., Dias, D. A., De Souza, D., Rupasinghe, T., Pyke, J., Tull, D., Roessner, U., McConville, M., and Speed, T. P. (2012) Normalizing and integrating metabolomics data. <i>Anal. Chem</i>. 84, 10768 –10776.</p></li>
<li><p>Tobin, J., Walach, J., de Beer, D., Williams, P. J., Filzmoser, P., and Walczak, B. (2017) Untargeted analysis of chromatographic data for green and fermented rooibos: Problem with size effect removal. <i>J. Chromatogr. A</i> 1525, 109 –115.</p></li>
<li><p>Wang, B., Wang, X. F., and Xi, Y. (2011) Normalizing bead-based microRNA expression data: A measurement error model-based approach. <i>Bioinformatics</i> 27, 1506 –1512.</p></li>
<li><p>Smolinska, A., Hauschild, A. C., Fijten, R. R., Dallinga, J. W., Baumbach, J., and van Schooten, F. J. (2014) Current breathomics—A review on data pre-processing techniques and machine learning in metabolomics breath analysis. <i>J. Breath Res</i>. 8, 027105.</p></li>
<li><p>Branson, O. E., and Freitas, M. A. (2016) A multi-model statistical approach for proteomic spectral count quantitation. <i>J. Proteomics</i> 144, 23–32.</p></li>
<li><p>Rausch, T. K., Schillert, A., Ziegler, A., Lu¨ king, A., Zucht, H. D., and Schulz-Knappe, P. (2016) Comparison of pre-processing methods for multiplex bead-based immunoassays. <i>BMC Genomics</i> 17, 601.</p></li>
<li><p>Lin, S. M., Du, P., Huber, W., and Kibbe, W. A. (2008) Model-based variance-stabilizing transformation for Illumina microarray data. <i>Nucleic Acids Res</i>. 36, e11.</p></li>
<li><p>Stacklies, W., Redestig, H., Scholz, M., Walther, D., and Selbig, J. (2007) pcaMethods—A bioconductor package providing PCA methods for incomplete data. <i>Bioinformatics</i> 23, 1164 –1167.</p></li>
<li><p>Troyanskaya, O., Cantor, M., Sherlock, G., Brown, P., Hastie, T., Tibshirani, R., Botstein, D., and Altman, R. B. (2001) Missing value estimation methods for DNA microarrays. <i>Bioinformatics</i> 17, 520 –525.</p></li>
</ol>

</body>

</html>
