# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NeedForSpeed1 <- function(D, S, pD, pS, nrow, N, N_len, ssq, B, overlaps, overlaps_P) {
    .Call('_EVALFQ_NeedForSpeed1', PACKAGE = 'EVALFQ', D, S, pD, pS, nrow, N, N_len, ssq, B, overlaps, overlaps_P)
}

NeedForSpeed2 <- function(D, pD, nrow, N, N_len, B, overlaps, overlaps_P) {
    .Call('_EVALFQ_NeedForSpeed2', PACKAGE = 'EVALFQ', D, pD, nrow, N, N_len, B, overlaps, overlaps_P)
}

pvalue <- function(a, b) {
    .Call('_EVALFQ_pvalue', PACKAGE = 'EVALFQ', a, b)
}

